osx_image: xcode10.2

language: node_js
node_js: "10"

os:
  - linux
  - osx

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
    - $HOME/.npm/_prebuilds

install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install yarn; fi
  - yarn

script:
- echo "Deploy linux version to GitHub"
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then yarn release --linux; fi

- echo "Deploy windows version to GitHub"
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then yarn release --win; fi

- echo "Deploy mac version to GitHub"
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then yarn release --mac; fi

before_cache:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then rm -rf $HOME/.cache/electron-builder/wine; fi

branches:
  only:
    - master